// para las rutas bases del api
export const URL_SERVICIOS = 'http://localhost:3000/';

export const TOKEN = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvIjp7InJvbGUiOiJBRE1JTl9ST0xFIiwiX2lkIjoiNWUzNjA0MTQwMDgwNGEzMzVjZDNmNDgwIiwibm9tYnJlIjoiTmVyaW8iLCJlbWFpbCI6Im5lcmlvQGdtYWlsLmNvbSIsImltZyI6Im51bGwiLCJwYXNzd29yZCI6IjopIiwiX192IjowfSwiaWF0IjoxNTgxNzg2NjkxLCJleHAiOjE1ODE4MDEwOTF9.FjWAXe4tIYhv03tFc2C3KqQPDMW39dduCK9MicKtDF0';
